export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_ONE_CHARACTER = "FETCH_ONE_CHARACTER";
export const FETCH_MORE_CHARACTERS = "FETCH_MORE_CHARACTERS";
export const LOADING_START = "LOADING_START";
export const LOADING_FINISH = "LOADING_FINISH";
export const LOADING_MORE_START = "LOADING_MORE_START";
export const LOADING_MORE_FINISH = "LOADING_MORE_FINISH";
